spring.application.name=delivery-service
server.port=8082

management.endpoints.web.exposure.include=*
management.health.rabbit.enabled=true
management.info.env.enabled=true

# Mongo placeholder
spring.data.mongodb.host=${MONGODB_HOST_NAME:localhost}
spring.data.mongodb.port=27017
spring.data.mongodb.database=delivery_service_db
spring.data.mongodb.auto-index-creation=true

# Kafka consumer
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=delivery-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.food.eat.authservice.dto.event,com.food.eat.deliveryservice.dto.event
spring.kafka.consumer.properties.spring.json.type.mapping=com.food.eat.authservice.dto.event.UserEvent:com.food.eat.deliveryservice.dto.event.UserEvent
