deploymentName: gateway-server
serviceName: gateway-server
appLabel: gateway-server
appName: gateway-server
replicaCount: 1
image:
  repository: gateway-server
  tag: v2
containerPort: 8092
service:
  type: LoadBalancer
  port: 8092
  targetPort: 8092
postgres_enabled: false
mongo_enabled: false
kafka_enabled: false
eureka_enabled: true
config_enabled: true
