server:
  port: 8085

spring:
  application:
    name: payment-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/food_delivery}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:pg12345}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8091/eureka/

kafka:
  enabled: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    try-it-out-enabled: true

bakong:
  base-url: "https://api-bakong.nbc.gov.kh"

