# ========================== MongoDB ====================================
mongodb:
  image: mongo:latest
  container_name: mongodb-micro-banking
  ports:
    - "27017:27017"
  volumes:
    - "./data:/data/db"
  networks:
    - microservice_food_delivery