spring.application.name=eureka-server
server.port=8091

spring.config.import=optional:configserver:http://localhost:8090
eureka.instance.hostname=localhost
eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false
eureka.client.service-url.defaultZone=https://${eureka.instance.hostname}:${server.port}/eureka/

management.endpoints.web.exposure.include=*
management.health.rabbit.enabled=true
management.info.env.enabled=true