spring.application.name=config-server
server.port=8090

spring.profiles.active=git
spring.cloud.config.server.git.uri=
spring.cloud.config.server.git.username=sorm_sophat04
spring.cloud.config.server.git.password=
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.default-label=main

management.endpoints.web.exposure.include=*
management.health.kafka.enabled=true
management.info.env.enabled=true

spring.security.oauth2.reourceserver.jwt.issuer-uri=http://auth-service:8080/realms/food-app