apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: food-delivery-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: food-delivery/config-server:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8090
          envFrom:
            - configMapRef:
                name: food-delivery-system
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: native
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8090
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8090
            initialDelaySeconds: 60
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: food-delivery-system
spec:
  selector:
    app: config-server
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
