apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-service
  namespace: food-delivery-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-service
  template:
    metadata:
      labels:
        app: delivery-service
    spec:
      containers:
        - name: delivery-service
          image: food-delivery/delivery-service:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: food-delivery-system
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: delivery-service
  namespace: food-delivery-system
spec:
  selector:
    app: delivery-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
