apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-service
  namespace: food-delivery-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-service
  template:
    metadata:
      labels:
        app: delivery-service
    spec:
      containers:
        - name: delivery-service
          image: food-delivery/delivery-service:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
