apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: food-delivery-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: food-delivery/eureka-server:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8091
