apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server-deployment
  namespace: food-delivery-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: food-delivery/eureka-server:v1
          ports:
            - containerPort: 8091
          envFrom:
            - configMapRef:
                name: food-delivery-system
          env:
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: food-delivery-system
                  key: EUREKA_APPLICATION_NAME
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8091
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8091
            initialDelaySeconds: 60
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: food-delivery-system
spec:
  selector:
    app: eureka-server
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091
