apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-service-deployment
  namespace: food-delivery-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: food-service
  template:
    metadata:
      labels:
        app: food-service
    spec:
      containers:
        - name: food-service
          image: food-delivery/food-service:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: food-delivery-system
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: food-delivery-system
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/food_delivery
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: pg12345
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: food-service
  namespace: food-delivery-system
spec:
  selector:
    app: food-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
