spring.application.name=delivery-service
server.port=8082

management.endpoints.web.exposure.include=*
management.health.rabbit.enabled=true
management.info.env.enabled=true

# Mongo placeholder
spring.data.mongodb.host=${MONGODB_HOST_NAME:localhost}
spring.data.mongodb.port=27017
spring.data.mongodb.database=delivery_service_db
spring.data.mongodb.auto-index-creation=true