apiVersion: v1
kind: ConfigMap
metadata:
  name: food-delivery-system
  namespace: food-delivery-system
data:
  SPRING_PROFILES_ACTIVE: default
  SPRING_CONFIG_IMPORT: "optional:configserver:http://config-server:8090/"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8091/eureka/"
  CONFIGSERVER_CLIENT_APPLICATION_NAME: config-server
  EUREKA_APPLICATION_NAME: eureka-server
  AUTH_APPLICATION_NAME: auth-service
  FOOD_APPLICATION_NAME: food-service
  ORDER_APPLICATION_NAME: order-service
  DELIVERY_APPLICATION_NAME: delivery-service
  RESTAURANT_APPLICATION_NAME: restaurant-service
  GATEWAY_APPLICATION_NAME: gateway-server
  KEYCLOAK_ADMIN: admin11
  KEYCLOAK_ADMIN_PASSWORD: admin
  MONGODB_HOST_NAME: mongodb
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: kafka:9092
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: "http://keycloak:7080/realms/master/protocol/openid-connect/certs"
